heat_template_version: 2018-08-31
description: create and attach volume

parameters:
  availability_zone: {type: string, default: nova}
  description: {type: string, default: ""}
  metadata: {type: json, default: {}}
  name: {type: string}
  size: {type: number, default: 0}
  volume_type: {type: string, default: standard}
  instance_uuid: {type: string}

conditions:
  volumeCreate: {not: {equals: [{get_param: size},0]}}

resources:
  volume:
    type: OS::Cinder::Volume
    condition: volumeCreate
    properties:
      availability_zone: {get_param: availability_zone}
      description: {get_param: description}
      metadata: {get_param: metadata}
      name: {get_param: name}
      size: {get_param: volume_size}
      volume_type: {get_param: volume_type}

  volumeAttachment:
    type: OS::Cinder::VolumeAttachment
    condition: volumeCreate
    properties:
      instance_uuid: {get_resource: server}
      volume_id: {get_resource: volume}

outputs:
  OS::stack_id: {value: {get_resource: volume}, condition: volumeCreate}
